// scaleMap.ts (new or shared)
export const scaleMap = {
  '6.5rem': {
    fontSize: '6.5rem',
    NeonTitleFontSize: '6.5rem',
    NeonSectionTitleFontSize: '6.5rem',
    NeonTextFontSize: '6.5rem',
    viewBoxHeight: 105,
    NeonTitleViewBoxHeight: 105,
    svgViewBoxHeight: 90,
    boxWidth: '220px',
    bulbSize: '15px',
    microphoneWidth: '30px',
    faceWidth: '100px',
    arrowWidth: '200px',
    arrowTextSize: '2em',
    cardsPerView: '1',

  },
  '7.5rem': {
    fontSize: '4rem',
    NeonTitleFontSize: '7.5rem',
    NeonSectionTitleFontSize: '7.5rem',
    NeonTextFontSize: '6rem',
    viewBoxHeight: 110,
    NeonTitleViewBoxHeight: 110,
    svgViewBoxHeight: 105,
    boxWidth: '280px',
    bulbSize: '18px',
    microphoneWidth: '60px',
    faceWidth: '190px',
    arrowWidth: '260px',
    arrowTextSize: '2.4em',
    cardsPerView: '2.25',
  },
  '8.5rem': {
    fontSize: '6rem',
    NeonTitleFontSize: '8.5rem',
    NeonSectionTitleFontSize: '6.5rem',
    NeonTextFontSize: '6rem',
    viewBoxHeight: 115,
    NeonTitleViewBoxHeight: 115,
    svgViewBoxHeight: 115,
    boxWidth: '320px',
    bulbSize: '22px',
    microphoneWidth: '70px',
    faceWidth: '220px',
    arrowWidth: '300px',
    arrowTextSize: '2.5em',
    cardsPerView: '3.25',
  },
} as const;

export type FontSizeKey = keyof typeof scaleMap;
